export const HELP_COMMANDS = [
  '<div class="gap"></div>',
  '<span class="command-help">COMANDOS DISPONIBLES:</span>',
  '═════════════════════════════════',
  '<span class="success">help (h)</span> - Muestra esta ayuda.',
  '<span class="success">about (a)</span> - Información personal.',
  '<span class="success">skills (s)</span> - Habilidades técnicas.',
  '<span class="success">projects (p)</span> - Proyectos realizados.',
  '<span class="success">contact (c)</span> - Información de contacto.',
  '<span class="success">clear/cls</span> - Limpia la terminal.',
  '<span class="success">menu (m)</span> - Abre menú del sistema.',
  '═════════════════════════════════'
];

export const ABOUT_COMMANDS = [
  '<div class="gap"></div>',
  '<span class="command-help">INFORMACIÓN PERSONAL</span>',
  '═════════════════════════════════',
  '<span class="info">Sujeto:</span> <b>Sergio Martínez Pérez.',
  '<span class="info">Profesión:</span> <b>Ingeniero/Desarrollador de Software</b>.',
  '<span class="info">Experiencia:</span> <b>Primera web 2003. Experiencia activa profesionalmente desde 2019.',
  '<span class="info">Ubicación:</span> <b>Barcelona, España</b>.',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<span class="command-help">DESCRIPCIÓN</span>',
  '<div class="gap"></div>',
  '<span class="success">Apasionado por crear soluciones innovadoras usando tecnologías modernas. Especializado en desarrollo web y todo tipo de aplicaciones usando <a href="https://angular.dev/" target="blank">Angular</a> en cualquiera de sus versiones.</span>',
  '<div class="gap"></div>',
  '<span class="success">Curiosidad, compromiso, fiabilidad son algunas de sus cualidades. Según los datos, ha entregado valor directo y sin demora durante <b>6 años</b> consecutivos. Ha trabajado en grandes compañias bajo entornos <a href="https://learn.microsoft.com/es-es/compliance/regulatory/offering-gxp" target="blank">GxP</a> y se ha enfrentado a despliegues en <b>producción</b> en varias ocasiones garantizando calidad y cumplimiento.</span>',
  '<div class="gap"></div>',
  '<span class="success">Nuestros estudios indican una comunicación efectiva con otros módulos del <b>equipo</b> y una visión enfocada en el producto y especialmente en el <b>cliente</b>. Protocolos de colaboración ejecutados con éxito en entornos de alta exigencia. Dispone de módulos de expansión libres para aumentar su potencia.</span>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<span class="success">- Nivel de adaptabilidad: <b>ÓPTIMO</b></span>',
  '<span class="success">- Disponibilidad: <b>2 SEMANAS</b></span>',
  '<span class="success">- Teletrabajo: <b>COMPATIBLE</b></span>',
  '<div class="gap"></div>',
  '═════════════════════════════════'
];

export const SKILLS_COMMANDS = [
  '<div class="gap"></div>',
  '<span class="command-help">HABILIDADES</span>',
  '═════════════════════════════════',
  '<b>Frontend</b>:',
  '  • <span class="success">TypeScript/JavaScript</span>',
  '  • <span class="success">Angular, React Native, Ionic, Astro, Cypress, Electron, Karma</span>',
  '  • <span class="success">HTML5, CSS3, SASS, RXJS, NGRX, TSX, DOM, Material Design</span>',
  '<div class="gap"></div>',
  '<b>Backend</b>:',
  '  • <span class="success">Node.js, NPM, NVM</span>',
  '  • <span class="success">Express, OAuth, JWT, Socket.io</span>',
  '  • <span class="success">MongoDB, SQLite, API REST</span>',
  '<div class="gap"></div>',
  '<b>DevOps</b>:',
  '  • <span class="success">Jenkins, Openshift, Netlify, Render, Visual Studio Code</span>',
  '  • <span class="success">Git, Bitbucket, Jira, Teams</span>',
  '  • <span class="success">Windows, MacOS</span>',
  '<div class="gap"></div>',
  '<b>Soft Skills</b>:',
  '  • <span class="success">Trabajo en equipo, inglés, pensamiento crítico, atención al detalle</span>',
  '  • <span class="success">Comprensión, superación, aprendizaje, paciencia, adaptabilidad</span>',
  '  • <span class="success">Empatía, compromiso, cumplimiento, resolución de problemas</span>',
  '<div class="gap"></div>',
  '═════════════════════════════════'
];

export const PROJECTS_COMMANDS = [
  '<div class="gap"></div>',
  '<span class="command-help">PROYECTOS DESTACADOS</span>',
  '═════════════════════════════════',
  '<b>[1] Mi Generali</b>',
  '<span class="success">Tech: Ionic, Java, SQL, Android/IOS</span>',
  '<span class="success">Descripción: Aplicación pública de la aseguradora <a href="https://www.generali.es/" target="blank">Generali</a> en el apartado de “Siniestros”, con corrección de errores, optimización de formularios, nuevas implementaciones y soporte desde un centro especializado de alto rendimiento brindando a los clientes una experiencia más simple, confiable y eficiente.</span>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<b>[2] Generali Tarjeta Visita</b>',
  '<span class="success">Tech: Angular, Java, SQL</span>',
  '<span class="success">Descripción: Página web pública para mostrar información sobre Agentes de la aseguradora <a href="https://www.generali.es/" target="blank">Generali</a>. Funciona como una tarjeta personal virtual. El identificador se comparte por la URL. <a href="https://www.generali.es/webapps/agentCard/#/home/foo" target="blank">Tarjeta Visita</a>.</span>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<b>[3] App Warehouse</b>',
  '<span class="success">Tech: Angular, Python, Django</span>',
  '<span class="success">Descripción:  Aplicación interna para <a href="https://www.boehringer-ingelheim.com/es" target="blank">Boehringer Ingelheim</a> diseñada como índice central de referencia de una de sus delegaciones de investigación, con un <b>CRUD</b> para administrar la información de las aplicaciones y ofrecer a los usuarios un acceso rápido, organizado y eficiente a sus consultas, incluyendo para cada aplicación su información detallada, imágenes, enlaces directos y recursos asociados.</span>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<b>[4] LOKI - Integration Studio</b>',
  '<span class="success">Tech: Angular, Node.js, Lua, Inmation, MongoDB</span>',
  '<span class="success">Descripción: Aplicación interna para <a href="https://www.boehringer-ingelheim.com/es" target="blank">Boehringer Ingelheim</a>, desarrollada bajo políticas <a href="https://learn.microsoft.com/es-es/compliance/regulatory/offering-gxp" target="blank">GxP</a> con el objetivo de automatizar procesos previamente manuales, permitiendo la integración y consulta de datos, gestión de usuarios, roles e idiomas, así como compatibilidad con hojas de cálculo <b>Excel</b> para la configuración de sistemas y fuentes de datos aplicadas a <b>procesos automáticos</b> de producción; un sistema auditado que incorpora documentación, registro, firmas electrónicas y generación de reportes en PDF, respaldado por un equipo multidisciplinario de UI/UX, especialistas, integradores, DevOps, QA, Power BI... que escucha activamente a los <b>usuarios</b>, desarrolla soluciones a medida mediante una metodología ágil, asegura el seguimiento de tareas y resultados, y fomenta la mejora continua a través del aprendizaje constante.</span>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<span class="command-help">PROYECTOS PERSONALES</span>',
  '═════════════════════════════════',
  '<b>[1] The Formatted Blog (2016)</b>',
  '<span class="success">Tech: Angular 17, Node.js, MongoDB</span>',
  '<span class="success">Descripción: Aplicación web para crear contenido basado en <b>markdown</b>. Contiene sistema de usuarios, sesiones, perfil, poder crear contenido y gestionarlo, editar, borrar, etc... Sistema de administración, los moderadores dedicen que contenido creado por los usuarios es visible dentro de la aplicación.</span>',
  '<div class="gap"></div>',
  '<span class="success">- Github: <a href="https://github.com/snakone/the-formatted-blog" target="blank">Code</a>',
  '<span class="success">- Link: <a href="https://formatted-blog.netlify.app/home" target="blank">The Formatted Blog</a>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<b>[2] TCG Pocket Cards (2024)</b>',
  '<span class="success">Tech: React Native, Expo, MongoDB</span>',
  '<span class="success">Descripción: Aplicación móvil y web del juego para móviles <a href="https://tcgpocket.pokemon.com/en-us/" target="blank">TCG Pocket</a>. Consulta cartas, crear mazos, colecciones e intercambios. Un programa que se inspira visualmente en el juego.</span>',
  '<div class="gap"></div>',
  '<span class="success">- Github: <a href="https://github.com/snakone/tcg-pocket-cards" target="blank">Code</a>',
  '<span class="success">- Link: <a href="https://tcg-pocket-cards.netlify.app/" target="blank">TCG Pocket Cards</a>',
  '<div class="gap"></div>',
  '<div class="gap"></div>',
  '<b>[3] Local Youtube Stalker (2025)</b>',
  '<span class="success">Tech: Angular, IA, Nodejs, Express</span>',
  '<span class="success">Descripción: Aplicación web que permite usar LLM sin coste gracias a <a href="https://ollama.com/" target="blank">Ollama</a>. Analiza vídeos de Youtube o páginas web de maneral local. Todo sin coste y de manera ilimitada.</span>',
  '<div class="gap"></div>',
  '<span class="success">- Github: <a href="https://github.com/snakone/local-youtube-stalker-LLM" target="blank">Code</a>',
  '<span class="success">- Link: <a href="https://localyoutubestalker.netlify.app/" target="blank">Local Youtube Stalker</a>',
  '═════════════════════════════════'
];

export const CONTACT_COMMANDS = [
  '<div class="gap"></div>',
  '<span class="command-help">INFORMACIÓN DE CONTACTO</span>',
  '═════════════════════════════════',
  '<span class="success">Email:</span> <a href="mailto:smartinez@knowmadmood.com">smartinez</a>',
  '<span class="success">LinkedIn:</span> <a href="https://www.linkedin.com/in/sergio-mart%C3%ADnez-9b933a13a/" target="blank">LinkedIn</a>',
  '<span class="success">GitHub:</span> <a href="https://github.com/snakone" target="blank">Github</a>',
  '<div class="gap"></div>',
  '<span class="info">¡CONECTEMOS!</span>',
  '<div class="gap"></div>',
  'Siempre abierto a nuevas oportunidades y colaboraciones, con especial interés en la <b>Inteligencia Artificial</b> y en generar soluciones innovadoras que aporten valor a los usuarios.',
  '═════════════════════════════════'
];